name: run_cmd

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run_bash_cmd
        env:
          GO111MODULE: on
        run: |
          ip a 
          curl ip.sb
        shell: bash
